lint:
  plugin_includes: false
  files_exist:
    - CODE_OF_CONDUCT.md
    - assets/nf-core-directrna_logo_light.png
    - docs/images/nf-core-directrna_logo_light.png
    - docs/images/nf-core-directrna_logo_dark.png
    - .github/workflows/nf-test.yml
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - nf-test.config
    - .github/workflows/awsfulltest.yml
    - ro-crate-metadata.json
    - tests/nextflow.config
    - nf-test.config
    - .github/actions/get-shards/action.yml
    - .github/actions/nf-test/action.yml
    - tests/default.nf.test
  files_unchanged:
    - conf/igenomes_ignored.config
    - LICENSE
    - .github/ISSUE_TEMPLATE/feature_request.yml
    - .github/PULL_REQUEST_TEMPLATE.md
    - .github/workflows/branch.yml
    - .github/workflows/linting_comment.yml
    - .github/workflows/linting.yml
    - assets/email_template.html
    - assets/email_template.txt
    - assets/sendmail_template.txt
    - docs/README.md
    - .gitignore
    - .github/CONTRIBUTING.md
    - CODE_OF_CONDUCT.md
    - assets/nf-core-directrna_logo_light.png
    - docs/images/nf-core-directrna_logo_light.png
    - docs/images/nf-core-directrna_logo_dark.png
    - .github/ISSUE_TEMPLATE/bug_report.yml
  multiqc_config:
    - report_comment
  nextflow_config: false
  #    - manifest.name
  #    - manifest.homePage
  nf_test_content: False
nf_core_version: 3.5.2
repository_type: pipeline
template:
  prefix: number-25
  skip: []
